/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  canonicalUrl?: string;
  noIndex?: boolean;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type NavLink = {
  _type: "navLink";
  label: string;
  href: string;
};

export type FirmDetails = {
  _id: string;
  _type: "firmDetails";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firmName: string;
  tagline?: string;
  phone: string;
  email: string;
  address?: {
    street: string;
    locality: string;
    region: string;
    postalCode: string;
  };
  hours?: {
    days: string;
    time: string;
  };
  socials?: Array<{
    platform: "facebook" | "instagram" | "linkedin" | "x" | "youtube";
    url: string;
    _type: "socialProfile";
    _key: string;
  }>;
  serviceAreas?: Array<{
    label: string;
    navLabel: string;
    href: string;
    _type: "serviceArea";
    _key: string;
  }>;
  footerNav?: Array<{
    heading: string;
    links?: Array<
      {
        _key: string;
      } & NavLink
    >;
    _type: "footerColumn";
    _key: string;
  }>;
  legalLinks?: Array<
    {
      _key: string;
    } & NavLink
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | BlockContent
  | SanityImageAssetReference
  | Seo
  | SanityImageCrop
  | SanityImageHotspot
  | NavLink
  | FirmDetails
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: src/sanity/firmDetails.ts
// Variable: FIRM_DETAILS_QUERY
// Query: *[_id == "firmDetails"][0]{  firmName,  tagline,  phone,  email,  address,  hours,  socials[]{ _key, platform, url },  serviceAreas[]{ _key, label, navLabel, href },  footerNav[]{ _key, heading, links[]{ _key, label, href } },  legalLinks[]{ _key, label, href }}
export type FIRM_DETAILS_QUERY_RESULT =
  | {
      firmName: null;
      tagline: null;
      phone: null;
      email: null;
      address: null;
      hours: null;
      socials: null;
      serviceAreas: null;
      footerNav: null;
      legalLinks: null;
    }
  | {
      firmName: string;
      tagline: string | null;
      phone: string;
      email: string;
      address: {
        street: string;
        locality: string;
        region: string;
        postalCode: string;
      } | null;
      hours: {
        days: string;
        time: string;
      } | null;
      socials: Array<{
        _key: string;
        platform: "facebook" | "instagram" | "linkedin" | "x" | "youtube";
        url: string;
      }> | null;
      serviceAreas: Array<{
        _key: string;
        label: string;
        navLabel: string;
        href: string;
      }> | null;
      footerNav: Array<{
        _key: string;
        heading: string;
        links: Array<{
          _key: string;
          label: string;
          href: string;
        }> | null;
      }> | null;
      legalLinks: Array<{
        _key: string;
        label: string;
        href: string;
      }> | null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_id == "firmDetails"][0]{\n  firmName,\n  tagline,\n  phone,\n  email,\n  address,\n  hours,\n  socials[]{ _key, platform, url },\n  serviceAreas[]{ _key, label, navLabel, href },\n  footerNav[]{ _key, heading, links[]{ _key, label, href } },\n  legalLinks[]{ _key, label, href }\n}': FIRM_DETAILS_QUERY_RESULT;
  }
}
