/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type ParagraphRun = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: never;
  markDefs?: Array<{
    href: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type AboutBody = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "lead" | "h3";
      listItem?: "bullet";
      markDefs?: Array<{
        href: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      quote: string;
      _type: "pullquote";
      _key: string;
    }
>;

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  canonicalUrl?: string;
  noIndex?: boolean;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type NavLink = {
  _type: "navLink";
  label: string;
  href: string;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  question: string;
  answer: string;
  showOnHomepage?: boolean;
  shortAnswer?: string;
  note?: string;
};

export type Award = {
  _id: string;
  _type: "award";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt: string;
  width: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  date: string;
  author: string;
  categories?: Array<
    "divorce" | "child-custody" | "child-support" | "domestic-violence"
  >;
  featured?: boolean;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  keyTakeaways?: Array<string>;
  body: BlockContent;
  legacyPath?: string;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type LocationPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "locationPage";
};

export type LocationPage = {
  _id: string;
  _type: "locationPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  navLabel: string;
  slug: Slug;
  location: LocationPageReference;
  parent?: LocationPageReference;
  subtitle?: string;
  body: BlockContent;
  faqs?: Array<{
    question: string;
    answer: BlockContent;
    _type: "faq";
    _key: string;
  }>;
  legacyPath?: string;
  seo?: Seo;
};

export type PracticeAreaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "practiceArea";
};

export type PracticeArea = {
  _id: string;
  _type: "practiceArea";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  navLabel: string;
  slug: Slug;
  parent?: PracticeAreaReference;
  subtitle?: string;
  body: BlockContent;
  faqs?: Array<{
    question: string;
    answer: BlockContent;
    _type: "faq";
    _key: string;
  }>;
  legacyPath?: string;
  seo?: Seo;
};

export type Attorney = {
  _id: string;
  _type: "attorney";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  role: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type StatsBand = {
  _id: string;
  _type: "statsBand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  stats: Array<{
    value: string;
    label: string;
    _type: "stat";
    _key: string;
  }>;
};

export type TestimonialReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "testimonial";
};

export type TestimonialsBand = {
  _id: string;
  _type: "testimonialsBand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow: string;
  headingLead: string;
  headingAccent?: string;
  lead: string;
  cardKicker: string;
  picks: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
  ctaLabel: string;
};

export type AwardsBand = {
  _id: string;
  _type: "awardsBand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading: string;
};

export type WhatDrivesUs = {
  _id: string;
  _type: "whatDrivesUs";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow: string;
  headingLead: string;
  headingAccent?: string;
  values: Array<{
    icon: "compassionate-approach" | "client-focused" | "experienced";
    title: string;
    text: string;
    _type: "value";
    _key: string;
  }>;
};

export type CaseEvaluationForm = {
  _id: string;
  _type: "caseEvaluationForm";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading: string;
  intro: string;
  submitLabel: string;
  privacyNote: string;
};

export type ConsultForm = {
  _id: string;
  _type: "consultForm";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: {
    eyebrow: string;
    headingLead: string;
    headingAccent?: string;
    leadLines: Array<string>;
  };
  form?: {
    cardTitle: string;
    cardIntro: string;
    submitLabel: string;
    privacyNote: string;
  };
};

export type PrivacyPolicyPage = {
  _id: string;
  _type: "privacyPolicyPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: {
    kicker: string;
    title: string;
  };
  intro: BlockContent;
  sections: Array<{
    heading: string;
    body: BlockContent;
    contactNote?: string;
    _type: "section";
    _key: string;
  }>;
  seo?: Seo;
};

export type HiringGuidePage = {
  _id: string;
  _type: "hiringGuidePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: {
    kicker: string;
    kickerHref?: string;
    title: string;
  };
  sections: Array<{
    heading: string;
    body: BlockContent;
    _type: "section";
    _key: string;
  }>;
  seo?: Seo;
};

export type NotFoundPage = {
  _id: string;
  _type: "notFoundPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: {
    kicker: string;
    title: string;
    deck: string;
  };
  routes: Array<{
    label: string;
    href: string;
    note: string;
    _type: "route";
    _key: string;
  }>;
  callLead: string;
  seo?: Seo;
};

export type ThankYouPage = {
  _id: string;
  _type: "thankYouPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  head?: {
    eyebrow: string;
    title: string;
  };
  band?: {
    headingLines: string;
    headingAccent?: string;
    headingTail?: string;
    lead: string;
    ctaLabel: string;
  };
  seo?: Seo;
};

export type SitemapPage = {
  _id: string;
  _type: "sitemapPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: {
    kicker: string;
    title: string;
    deckTemplate: string;
  };
  seo?: Seo;
};

export type ClientPortalPage = {
  _id: string;
  _type: "clientPortalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: {
    kicker: string;
    title: string;
    deck: string;
  };
  groups: Array<{
    heading: string;
    blurb: string;
    actions: Array<{
      label: string;
      note: string;
      href: string;
      style: "btn--gold" | "btn--outline";
      external?: boolean;
      download?: boolean;
      _type: "action";
      _key: string;
    }>;
    _type: "group";
    _key: string;
  }>;
  seo?: Seo;
};

export type VideoCenterPage = {
  _id: string;
  _type: "videoCenterPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: {
    eyebrow: string;
    title: string;
    intro: string;
  };
  seo?: Seo;
};

export type FaqPage = {
  _id: string;
  _type: "faqPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: {
    eyebrow: string;
    title: string;
    intro: string;
  };
  seo?: Seo;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    eyebrow: string;
    title: string;
    lead: string;
  };
  findUs?: {
    eyebrow: string;
    headingLead: string;
    headingAccent?: string;
    headingTail?: string;
  };
  seo?: Seo;
};

export type TestimonialsPage = {
  _id: string;
  _type: "testimonialsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    eyebrow: string;
    headingLead: string;
    headingAccent?: string;
    headingTail?: string;
    lead: string;
    ctaLabel: string;
  };
  wall?: {
    eyebrow: string;
    headingLead: string;
    headingAccent?: string;
    headingTail?: string;
    lead: string;
    cardKicker: string;
  };
  seo?: Seo;
};

export type BlogPage = {
  _id: string;
  _type: "blogPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: {
    eyebrow: string;
    title: string;
    intro: string;
  };
  seo?: Seo;
};

export type PracticeAreasPage = {
  _id: string;
  _type: "practiceAreasPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    eyebrow: string;
    headingLead: string;
    headingAccent?: string;
    headingTail?: string;
    lead: string;
    ctaLabel: string;
  };
  featured?: {
    eyebrow: string;
    headingLead: string;
    headingAccent?: string;
    headingTail?: string;
    lead: string;
    cards: Array<{
      areaId: string;
      label?: string;
      icon:
        | "divorce"
        | "child-custody"
        | "family-law"
        | "child-support"
        | "property-division"
        | "modifications";
      text: string;
      _type: "card";
      _key: string;
    }>;
  };
  allAreas?: {
    eyebrow: string;
    headingLead: string;
    headingAccent?: string;
    headingTail?: string;
  };
  seo?: Seo;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    eyebrow: string;
    headingLead: string;
    headingAccent?: string;
    headingTail?: string;
    lead: string;
    ctaLabel: string;
  };
  whoWeAre?: {
    eyebrow: string;
    headingLead: string;
    headingAccent?: string;
    headingTail?: string;
    paragraphs: ParagraphRun;
    ctaLabel: string;
  };
  promise?: {
    quoteLead: string;
    quoteAccent?: string;
    quoteTail?: string;
  };
  meetPapa?: {
    eyebrow: string;
    chips: Array<{
      icon: "scales" | "star" | "heart";
      value: string;
      label: string;
      _type: "chip";
      _key: string;
    }>;
    paragraphs: ParagraphRun;
    milestones: Array<{
      when: string;
      title: string;
      text: string;
      _type: "milestone";
      _key: string;
    }>;
  };
  whyFamilyLaw?: {
    eyebrow: string;
    headingLead: string;
    headingAccent?: string;
    headingTail?: string;
    paragraphs: ParagraphRun;
  };
  seo?: Seo;
};

export type VideoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "video";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    eyebrow: string;
    headingLines: string;
    headingAccent?: string;
    lead: string;
    ctaLabel: string;
    stats: Array<{
      value: string;
      label: string;
      _type: "stat";
      _key: string;
    }>;
  };
  about?: {
    eyebrow: string;
    headingLead: string;
    headingAccent?: string;
    videoLabel: string;
    videoCaption: string;
    video: VideoReference;
    pullQuote: TestimonialReference;
    body: AboutBody;
    ctaLabel: string;
  };
  practiceAreas?: {
    eyebrow: string;
    headingLead: string;
    headingAccent?: string;
    intro: string;
    areas: Array<{
      icon:
        | "divorce"
        | "child-custody"
        | "family-law"
        | "child-support"
        | "property-division"
        | "modifications";
      title: string;
      href: string;
      text: string;
      _type: "area";
      _key: string;
    }>;
    ctaLabel: string;
  };
  featuredAttorney?: {
    eyebrow: string;
    quote: string;
    paragraphs: ParagraphRun;
    ctaLabel: string;
    badgeYears: number;
    badgeLabelLines: Array<string>;
  };
  sellingPoints?: {
    eyebrow: string;
    headingLead: string;
    headingAccent?: string;
    points: Array<{
      icon:
        | "compassionate-approach"
        | "client-focused"
        | "experienced"
        | "flexible-payments";
      title: string;
      text: string;
      _type: "point";
      _key: string;
    }>;
  };
  faq?: {
    eyebrow: string;
    headingLead: string;
    headingAccent?: string;
  };
  videoReels?: {
    eyebrow: string;
    headingLead: string;
    headingAccent?: string;
    picks: Array<
      {
        _key: string;
      } & VideoReference
    >;
    ctaLabel: string;
  };
  community?: {
    eyebrow: string;
    headingLead: string;
    headingAccent?: string;
    paragraphs: ParagraphRun;
    ctaLabel: string;
    tileTitle: string;
    tileText: string;
  };
  guideRequest?: {
    eyebrow: string;
    headingLead: string;
    headingAccent?: string;
    lead: string;
    offer: string;
  };
  blog?: {
    eyebrow: string;
    headingLead: string;
    headingAccent?: string;
    ctaLabel: string;
  };
  seo?: Seo;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  lead: string;
  body: string;
  name: string;
  matter: string;
};

export type Video = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title: string;
  wistiaId: string;
  label: "The Firm" | "Quick Answer";
  aspect: "16/9" | "9/16";
  poster: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  reelPoster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type FirmDetails = {
  _id: string;
  _type: "firmDetails";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firmName: string;
  tagline?: string;
  phone: string;
  email: string;
  address?: {
    street: string;
    locality: string;
    region: string;
    postalCode: string;
  };
  hours?: {
    days: string;
    time: string;
  };
  socials?: Array<{
    platform: "facebook" | "instagram" | "linkedin" | "x" | "youtube";
    url: string;
    _type: "socialProfile";
    _key: string;
  }>;
  serviceAreas?: Array<{
    label: string;
    navLabel: string;
    href: string;
    _type: "serviceArea";
    _key: string;
  }>;
  footerNav?: Array<{
    heading: string;
    links?: Array<
      {
        _key: string;
      } & NavLink
    >;
    _type: "footerColumn";
    _key: string;
  }>;
  legalLinks?: Array<
    {
      _key: string;
    } & NavLink
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ParagraphRun
  | AboutBody
  | BlockContent
  | SanityImageAssetReference
  | Seo
  | NavLink
  | Faq
  | Award
  | SanityImageCrop
  | SanityImageHotspot
  | BlogPost
  | Slug
  | LocationPageReference
  | LocationPage
  | PracticeAreaReference
  | PracticeArea
  | Attorney
  | StatsBand
  | TestimonialReference
  | TestimonialsBand
  | AwardsBand
  | WhatDrivesUs
  | CaseEvaluationForm
  | ConsultForm
  | PrivacyPolicyPage
  | HiringGuidePage
  | NotFoundPage
  | ThankYouPage
  | SitemapPage
  | ClientPortalPage
  | VideoCenterPage
  | FaqPage
  | ContactPage
  | TestimonialsPage
  | BlogPage
  | PracticeAreasPage
  | AboutPage
  | VideoReference
  | HomePage
  | Testimonial
  | Video
  | FirmDetails
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/aboutPage.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_id == "aboutPage"][0]{    hero{ eyebrow, headingLead, headingAccent, headingTail, lead, ctaLabel },    whoWeAre{ eyebrow, headingLead, headingAccent, headingTail, paragraphs, ctaLabel },    promise{ quoteLead, quoteAccent, quoteTail },    meetPapa{ eyebrow, chips[]{ icon, value, label }, paragraphs, milestones[]{ when, title, text } },    whyFamilyLaw{ eyebrow, headingLead, headingAccent, headingTail, paragraphs }  }
export type ABOUT_PAGE_QUERY_RESULT =
  | {
      hero: null;
      whoWeAre: null;
      promise: null;
      meetPapa: null;
      whyFamilyLaw: null;
    }
  | {
      hero: {
        eyebrow: string;
        headingLead: null;
        headingAccent: null;
        headingTail: null;
        lead: string;
        ctaLabel: null;
      } | null;
      whoWeAre: null;
      promise: null;
      meetPapa: null;
      whyFamilyLaw: null;
    }
  | {
      hero: {
        eyebrow: string;
        headingLead: null;
        headingAccent: string | null;
        headingTail: null;
        lead: string;
        ctaLabel: string;
      } | null;
      whoWeAre: null;
      promise: null;
      meetPapa: null;
      whyFamilyLaw: null;
    }
  | {
      hero: {
        eyebrow: string;
        headingLead: string;
        headingAccent: string | null;
        headingTail: string | null;
        lead: string;
        ctaLabel: string;
      } | null;
      whoWeAre: null;
      promise: null;
      meetPapa: null;
      whyFamilyLaw: null;
    }
  | {
      hero: {
        eyebrow: string;
        headingLead: string;
        headingAccent: string | null;
        headingTail: string | null;
        lead: string;
        ctaLabel: string;
      } | null;
      whoWeAre: {
        eyebrow: string;
        headingLead: string;
        headingAccent: string | null;
        headingTail: string | null;
        paragraphs: ParagraphRun;
        ctaLabel: string;
      } | null;
      promise: {
        quoteLead: string;
        quoteAccent: string | null;
        quoteTail: string | null;
      } | null;
      meetPapa: {
        eyebrow: string;
        chips: Array<{
          icon: "heart" | "scales" | "star";
          value: string;
          label: string;
        }>;
        paragraphs: ParagraphRun;
        milestones: Array<{
          when: string;
          title: string;
          text: string;
        }>;
      } | null;
      whyFamilyLaw: {
        eyebrow: string;
        headingLead: string;
        headingAccent: string | null;
        headingTail: string | null;
        paragraphs: ParagraphRun;
      } | null;
    }
  | null;

// Source: src/sanity/awards.ts
// Variable: AWARDS_QUERY
// Query: {  "heading": *[_id == "awardsBand"][0].heading,  "badges": *[_type == "award"] | order(orderRank){    "id": _id,    alt,    width,    image{ asset, "dimensions": asset->metadata.dimensions }  }}
export type AWARDS_QUERY_RESULT = {
  heading: null | string;
  badges: Array<{
    id: string;
    alt: string;
    width: number;
    image: {
      asset: SanityImageAssetReference | null;
      dimensions: SanityImageDimensions | null;
    };
  }>;
};

// Source: src/sanity/blogPage.ts
// Variable: BLOG_PAGE_QUERY
// Query: *[_id == "blogPage"][0]{ header{ eyebrow, title, intro } }
export type BLOG_PAGE_QUERY_RESULT =
  | {
      header: null;
    }
  | {
      header: {
        eyebrow: null;
        title: string;
        intro: null;
      } | null;
    }
  | {
      header: {
        eyebrow: string;
        title: null;
        intro: null;
      } | null;
    }
  | {
      header: {
        eyebrow: string;
        title: string;
        intro: string;
      } | null;
    }
  | null;

// Source: src/sanity/blogPosts.ts
// Variable: BLOG_POSTS_ALL_QUERY
// Query: *[_type == "blogPost"]{    "id": slug.current,    "data": {      title,      date,      author,      "categories": coalesce(categories, []),      featured,      "keyTakeaways": coalesce(keyTakeaways, []),      "description": seo.metaDescription,      "seoTitle": seo.metaTitle,      "imageAlt": coalesce(image.alt, ""),      "image": image{        asset,        "dimensions": asset->metadata.dimensions      }    },    body,    "noIndex": seo.noIndex,    _updatedAt  }
export type BLOG_POSTS_ALL_QUERY_RESULT = Array<{
  id: string;
  data: {
    title: string;
    date: string;
    author: string;
    categories:
      | Array<never>
      | Array<
          "child-custody" | "child-support" | "divorce" | "domestic-violence"
        >;
    featured: boolean | null;
    keyTakeaways: Array<string> | Array<never>;
    description: string | null;
    seoTitle: string | null;
    imageAlt: string | "";
    image: {
      asset: SanityImageAssetReference | null;
      dimensions: SanityImageDimensions | null;
    } | null;
  };
  body: BlockContent;
  noIndex: boolean | null;
  _updatedAt: string;
}>;

// Source: src/sanity/clientPortalPage.ts
// Variable: QUERY
// Query: *[_id == "clientPortalPage"][0]{    header{ kicker, title, deck },    groups[]{ heading, blurb, actions[]{ label, note, href, style, external, download } }  }
export type QUERY_RESULT =
  | {
      header: {
        kicker: string;
        title: string;
        deck: string;
      } | null;
      groups: Array<{
        heading: string;
        blurb: string;
        actions: Array<{
          label: string;
          note: string;
          href: string;
          style: "btn--gold" | "btn--outline";
          external: boolean | null;
          download: boolean | null;
        }>;
      }>;
    }
  | {
      header: null;
      groups: null;
    }
  | {
      header: {
        kicker: null;
        title: null;
        deck: null;
      } | null;
      groups: null;
    }
  | {
      header: {
        kicker: null;
        title: string;
        deck: null;
      } | null;
      groups: null;
    }
  | {
      header: {
        kicker: string;
        title: string;
        deck: null;
      } | null;
      groups: null;
    }
  | {
      header: {
        kicker: string;
        title: string;
        deck: string;
      } | null;
      groups: null;
    }
  | null;

// Source: src/sanity/consultForm.ts
// Variable: CONSULT_FORM_QUERY
// Query: *[_id == "consultForm"][0]{    header{ eyebrow, headingLead, headingAccent, leadLines },    form{ cardTitle, cardIntro, submitLabel, privacyNote }  }
export type CONSULT_FORM_QUERY_RESULT =
  | {
      header: null;
      form: null;
    }
  | {
      header: {
        eyebrow: null;
        headingLead: null;
        headingAccent: null;
        leadLines: null;
      } | null;
      form: null;
    }
  | {
      header: {
        eyebrow: string;
        headingLead: null;
        headingAccent: null;
        leadLines: null;
      } | null;
      form: null;
    }
  | {
      header: {
        eyebrow: string;
        headingLead: string;
        headingAccent: string | null;
        leadLines: Array<string>;
      } | null;
      form: {
        cardTitle: string;
        cardIntro: string;
        submitLabel: string;
        privacyNote: string;
      } | null;
    }
  | null;

// Source: src/sanity/contactPage.ts
// Variable: CONTACT_PAGE_QUERY
// Query: *[_id == "contactPage"][0]{    hero{ eyebrow, title, lead },    findUs{ eyebrow, headingLead, headingAccent, headingTail }  }
export type CONTACT_PAGE_QUERY_RESULT =
  | {
      hero: null;
      findUs: null;
    }
  | {
      hero: {
        eyebrow: string;
        title: null;
        lead: string;
      } | null;
      findUs: null;
    }
  | {
      hero: {
        eyebrow: string;
        title: string;
        lead: string;
      } | null;
      findUs: {
        eyebrow: string;
        headingLead: string;
        headingAccent: string | null;
        headingTail: string | null;
      } | null;
    }
  | null;

// Source: src/sanity/faqs.ts
// Variable: FAQS_QUERY
// Query: *[_type == "faq"] | order(orderRank){ question, answer, shortAnswer, showOnHomepage }
export type FAQS_QUERY_RESULT = Array<{
  question: string;
  answer: string;
  shortAnswer: string | null;
  showOnHomepage: boolean | null;
}>;

// Source: src/sanity/firmDetails.ts
// Variable: FIRM_DETAILS_QUERY
// Query: *[_id == "firmDetails"][0]{  firmName,  tagline,  phone,  email,  address,  hours,  socials[]{ _key, platform, url },  serviceAreas[]{ _key, label, navLabel, href },  footerNav[]{ _key, heading, links[]{ _key, label, href } },  legalLinks[]{ _key, label, href }}
export type FIRM_DETAILS_QUERY_RESULT =
  | {
      firmName: null;
      tagline: null;
      phone: null;
      email: null;
      address: null;
      hours: null;
      socials: null;
      serviceAreas: null;
      footerNav: null;
      legalLinks: null;
    }
  | {
      firmName: string;
      tagline: string | null;
      phone: string;
      email: string;
      address: {
        street: string;
        locality: string;
        region: string;
        postalCode: string;
      } | null;
      hours: {
        days: string;
        time: string;
      } | null;
      socials: Array<{
        _key: string;
        platform: "facebook" | "instagram" | "linkedin" | "x" | "youtube";
        url: string;
      }> | null;
      serviceAreas: Array<{
        _key: string;
        label: string;
        navLabel: string;
        href: string;
      }> | null;
      footerNav: Array<{
        _key: string;
        heading: string;
        links: Array<{
          _key: string;
          label: string;
          href: string;
        }> | null;
      }> | null;
      legalLinks: Array<{
        _key: string;
        label: string;
        href: string;
      }> | null;
    }
  | null;

// Source: src/sanity/homePage.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "homePage"][0]{    hero{ eyebrow, headingLines, headingAccent, lead, ctaLabel, stats[]{ value, label } },    about{      eyebrow, headingLead, headingAccent, videoLabel, videoCaption, body, ctaLabel,      video->{ "id": wistiaId, title, poster{ asset, "dimensions": asset->metadata.dimensions } }    },    practiceAreas{ eyebrow, headingLead, headingAccent, intro, ctaLabel, areas[]{ icon, title, href, text } },    featuredAttorney{ eyebrow, quote, paragraphs, ctaLabel, badgeYears, badgeLabelLines },    sellingPoints{ eyebrow, headingLead, headingAccent, points[]{ icon, title, text } },    faq{ eyebrow, headingLead, headingAccent },    videoReels{ eyebrow, headingLead, headingAccent, ctaLabel },    community{ eyebrow, headingLead, headingAccent, paragraphs, ctaLabel, tileTitle, tileText },    guideRequest{ eyebrow, headingLead, headingAccent, lead, offer },    blog{ eyebrow, headingLead, headingAccent, ctaLabel }  }
export type HOME_PAGE_QUERY_RESULT =
  | {
      hero: null;
      about: null;
      practiceAreas: null;
      featuredAttorney: null;
      sellingPoints: null;
      faq: null;
      videoReels: null;
      community: null;
      guideRequest: null;
      blog: null;
    }
  | {
      hero: {
        eyebrow: string;
        headingLines: null;
        headingAccent: null;
        lead: string;
        ctaLabel: null;
        stats: null;
      } | null;
      about: null;
      practiceAreas: null;
      featuredAttorney: null;
      sellingPoints: null;
      faq: null;
      videoReels: null;
      community: null;
      guideRequest: null;
      blog: null;
    }
  | {
      hero: {
        eyebrow: string;
        headingLines: null;
        headingAccent: string | null;
        lead: string;
        ctaLabel: string;
        stats: null;
      } | null;
      about: null;
      practiceAreas: null;
      featuredAttorney: null;
      sellingPoints: null;
      faq: null;
      videoReels: null;
      community: null;
      guideRequest: null;
      blog: null;
    }
  | {
      hero: {
        eyebrow: string;
        headingLines: string;
        headingAccent: string | null;
        lead: string;
        ctaLabel: string;
        stats: Array<{
          value: string;
          label: string;
        }>;
      } | null;
      about: {
        eyebrow: string;
        headingLead: string;
        headingAccent: string | null;
        videoLabel: string;
        videoCaption: string;
        body: AboutBody;
        ctaLabel: string;
        video: {
          id: string;
          title: string;
          poster: {
            asset: SanityImageAssetReference | null;
            dimensions: SanityImageDimensions | null;
          };
        };
      } | null;
      practiceAreas: {
        eyebrow: string;
        headingLead: string;
        headingAccent: string | null;
        intro: string;
        ctaLabel: string;
        areas: Array<{
          icon:
            | "child-custody"
            | "child-support"
            | "divorce"
            | "family-law"
            | "modifications"
            | "property-division";
          title: string;
          href: string;
          text: string;
        }>;
      } | null;
      featuredAttorney: {
        eyebrow: string;
        quote: string;
        paragraphs: ParagraphRun;
        ctaLabel: string;
        badgeYears: number;
        badgeLabelLines: Array<string>;
      } | null;
      sellingPoints: {
        eyebrow: string;
        headingLead: string;
        headingAccent: string | null;
        points: Array<{
          icon:
            | "client-focused"
            | "compassionate-approach"
            | "experienced"
            | "flexible-payments";
          title: string;
          text: string;
        }>;
      } | null;
      faq: {
        eyebrow: string;
        headingLead: string;
        headingAccent: string | null;
      } | null;
      videoReels: {
        eyebrow: string;
        headingLead: string;
        headingAccent: string | null;
        ctaLabel: string;
      } | null;
      community: {
        eyebrow: string;
        headingLead: string;
        headingAccent: string | null;
        paragraphs: ParagraphRun;
        ctaLabel: string;
        tileTitle: string;
        tileText: string;
      } | null;
      guideRequest: {
        eyebrow: string;
        headingLead: string;
        headingAccent: string | null;
        lead: string;
        offer: string;
      } | null;
      blog: {
        eyebrow: string;
        headingLead: string;
        headingAccent: string | null;
        ctaLabel: string;
      } | null;
    }
  | null;

// Source: src/sanity/locationPages.ts
// Variable: LOCATION_PAGES_ALL_QUERY
// Query: *[_type == "locationPage"]{    "id": slug.current,    "data": {      title,      navLabel,      subtitle,      "parent": parent->slug.current,      "location": location->slug.current,      "description": seo.metaDescription,      "seoTitle": seo.metaTitle,      "faqs": coalesce(faqs[]{ _key, question, answer }, [])    },    body,    "noIndex": seo.noIndex,    "canonicalUrl": seo.canonicalUrl,    _updatedAt  }
export type LOCATION_PAGES_ALL_QUERY_RESULT = Array<{
  id: string;
  data: {
    title: string;
    navLabel: string;
    subtitle: string | null;
    parent: string | null;
    location: string;
    description: string | null;
    seoTitle: string | null;
    faqs:
      | Array<{
          _key: string;
          question: string;
          answer: BlockContent;
        }>
      | Array<never>;
  };
  body: BlockContent;
  noIndex: boolean | null;
  canonicalUrl: string | null;
  _updatedAt: string;
}>;

// Source: src/sanity/practiceAreas.ts
// Variable: PRACTICE_AREAS_ALL_QUERY
// Query: *[_type == "practiceArea"]{    "id": slug.current,    "data": {      title,      navLabel,      subtitle,      "parent": parent->slug.current,      "description": seo.metaDescription,      "seoTitle": seo.metaTitle,      "faqs": coalesce(faqs[]{ _key, question, answer }, [])    },    body,    "noIndex": seo.noIndex,    "canonicalUrl": seo.canonicalUrl,    _updatedAt  }
export type PRACTICE_AREAS_ALL_QUERY_RESULT = Array<{
  id: string;
  data: {
    title: string;
    navLabel: string;
    subtitle: string | null;
    parent: string | null;
    description: string | null;
    seoTitle: string | null;
    faqs:
      | Array<{
          _key: string;
          question: string;
          answer: BlockContent;
        }>
      | Array<never>;
  };
  body: BlockContent;
  noIndex: boolean | null;
  canonicalUrl: string | null;
  _updatedAt: string;
}>;

// Source: src/sanity/practiceAreasPage.ts
// Variable: PRACTICE_AREAS_PAGE_QUERY
// Query: *[_id == "practiceAreasPage"][0]{    hero{ eyebrow, headingLead, headingAccent, headingTail, lead, ctaLabel },    featured{      eyebrow, headingLead, headingAccent, headingTail, lead,      cards[]{ areaId, label, icon, text }    },    allAreas{ eyebrow, headingLead, headingAccent, headingTail }  }
export type PRACTICE_AREAS_PAGE_QUERY_RESULT =
  | {
      hero: null;
      featured: null;
      allAreas: null;
    }
  | {
      hero: {
        eyebrow: string;
        headingLead: null;
        headingAccent: null;
        headingTail: null;
        lead: string;
        ctaLabel: null;
      } | null;
      featured: null;
      allAreas: null;
    }
  | {
      hero: {
        eyebrow: string;
        headingLead: null;
        headingAccent: string | null;
        headingTail: null;
        lead: string;
        ctaLabel: string;
      } | null;
      featured: null;
      allAreas: null;
    }
  | {
      hero: {
        eyebrow: string;
        headingLead: string;
        headingAccent: string | null;
        headingTail: string | null;
        lead: string;
        ctaLabel: string;
      } | null;
      featured: null;
      allAreas: null;
    }
  | {
      hero: {
        eyebrow: string;
        headingLead: string;
        headingAccent: string | null;
        headingTail: string | null;
        lead: string;
        ctaLabel: string;
      } | null;
      featured: {
        eyebrow: string;
        headingLead: string;
        headingAccent: string | null;
        headingTail: string | null;
        lead: string;
        cards: Array<{
          areaId: string;
          label: string | null;
          icon:
            | "child-custody"
            | "child-support"
            | "divorce"
            | "family-law"
            | "modifications"
            | "property-division";
          text: string;
        }>;
      } | null;
      allAreas: {
        eyebrow: string;
        headingLead: string;
        headingAccent: string | null;
        headingTail: string | null;
      } | null;
    }
  | null;

// Source: src/sanity/siteWide.ts
// Variable: SITE_WIDE_CASE_EVALUATION_QUERY
// Query: *[_id == "caseEvaluationForm"][0]{ heading, intro, submitLabel, privacyNote }
export type SITE_WIDE_CASE_EVALUATION_QUERY_RESULT =
  | {
      heading: null;
      intro: BlockContent;
      submitLabel: null;
      privacyNote: null;
    }
  | {
      heading: null;
      intro: null;
      submitLabel: null;
      privacyNote: null;
    }
  | {
      heading: string;
      intro: null;
      submitLabel: null;
      privacyNote: null;
    }
  | {
      heading: string;
      intro: string;
      submitLabel: string;
      privacyNote: string;
    }
  | null;

// Source: src/sanity/siteWide.ts
// Variable: SITE_WIDE_ATTORNEY_QUERY
// Query: *[_id == "attorney"][0]{    name,    role,    photo{ asset, "dimensions": asset->metadata.dimensions }  }
export type SITE_WIDE_ATTORNEY_QUERY_RESULT =
  | {
      name: null;
      role: null;
      photo: null;
    }
  | {
      name: string;
      role: null;
      photo: null;
    }
  | {
      name: string;
      role: string;
      photo: {
        asset: SanityImageAssetReference | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    }
  | null;

// Source: src/sanity/statsBand.ts
// Variable: STATS_BAND_QUERY
// Query: *[_id == "statsBand"][0]{ stats[]{ value, label } }
export type STATS_BAND_QUERY_RESULT =
  | {
      stats: Array<{
        value: string;
        label: string;
      }>;
    }
  | {
      stats: null;
    }
  | null;

// Source: src/sanity/testimonials.ts
// Variable: TESTIMONIALS_ALL_QUERY
// Query: *[_type == "testimonial"] | order(orderRank) {    _id, lead, body, name, matter  }
export type TESTIMONIALS_ALL_QUERY_RESULT = Array<{
  _id: string;
  lead: string;
  body: string;
  name: string;
  matter: string;
}>;

// Source: src/sanity/testimonials.ts
// Variable: TESTIMONIALS_PULL_QUOTE_QUERY
// Query: *[_id == "homePage"][0].about.pullQuote->{ _id, lead, body, name, matter }
export type TESTIMONIALS_PULL_QUOTE_QUERY_RESULT = {
  _id: string;
  lead: string;
  body: string;
  name: string;
  matter: string;
} | null;

// Source: src/sanity/testimonials.ts
// Variable: TESTIMONIALS_BAND_QUERY
// Query: *[_id == "testimonialsBand"][0]{    eyebrow, headingLead, headingAccent, lead, cardKicker, ctaLabel,    "picks": picks[]->{ _id, lead, body, name, matter }  }
export type TESTIMONIALS_BAND_QUERY_RESULT =
  | {
      eyebrow: null;
      headingLead: null;
      headingAccent: null;
      lead: null;
      cardKicker: null;
      ctaLabel: null;
      picks: null;
    }
  | {
      eyebrow: null;
      headingLead: null;
      headingAccent: null;
      lead: string;
      cardKicker: null;
      ctaLabel: null;
      picks: null;
    }
  | {
      eyebrow: string;
      headingLead: string;
      headingAccent: string | null;
      lead: null;
      cardKicker: null;
      ctaLabel: null;
      picks: null;
    }
  | {
      eyebrow: string;
      headingLead: string;
      headingAccent: string | null;
      lead: string;
      cardKicker: string;
      ctaLabel: string;
      picks: Array<{
        _id: string;
        lead: string;
        body: string;
        name: string;
        matter: string;
      }>;
    }
  | null;

// Source: src/sanity/testimonialsPage.ts
// Variable: TESTIMONIALS_PAGE_QUERY
// Query: *[_id == "testimonialsPage"][0]{    hero{ eyebrow, headingLead, headingAccent, headingTail, lead, ctaLabel },    wall{ eyebrow, headingLead, headingAccent, headingTail, lead, cardKicker }  }
export type TESTIMONIALS_PAGE_QUERY_RESULT =
  | {
      hero: null;
      wall: null;
    }
  | {
      hero: {
        eyebrow: string;
        headingLead: null;
        headingAccent: null;
        headingTail: null;
        lead: string;
        ctaLabel: null;
      } | null;
      wall: null;
    }
  | {
      hero: {
        eyebrow: string;
        headingLead: null;
        headingAccent: string | null;
        headingTail: null;
        lead: string;
        ctaLabel: string;
      } | null;
      wall: null;
    }
  | {
      hero: {
        eyebrow: string;
        headingLead: string;
        headingAccent: string | null;
        headingTail: string | null;
        lead: string;
        ctaLabel: string;
      } | null;
      wall: null;
    }
  | {
      hero: {
        eyebrow: string;
        headingLead: string;
        headingAccent: string | null;
        headingTail: string | null;
        lead: string;
        ctaLabel: string;
      } | null;
      wall: {
        eyebrow: string;
        headingLead: string;
        headingAccent: string | null;
        headingTail: string | null;
        lead: string;
        cardKicker: string;
      } | null;
    }
  | null;

// Source: src/sanity/videos.ts
// Variable: VIDEOS_QUERY
// Query: *[_type == "video"] | order(orderRank){    "id": wistiaId,    title,    label,    aspect,    poster{ asset, "dimensions": asset->metadata.dimensions },    reelPoster{ asset, "dimensions": asset->metadata.dimensions }  }
export type VIDEOS_QUERY_RESULT = Array<{
  id: string;
  title: string;
  label: "Quick Answer" | "The Firm";
  aspect: "16/9" | "9/16";
  poster: {
    asset: SanityImageAssetReference | null;
    dimensions: SanityImageDimensions | null;
  };
  reelPoster: {
    asset: SanityImageAssetReference | null;
    dimensions: SanityImageDimensions | null;
  } | null;
}>;

// Source: src/sanity/videos.ts
// Variable: REEL_PICKS_QUERY
// Query: *[_id == "homePage"][0].videoReels.picks[]->wistiaId
export type REEL_PICKS_QUERY_RESULT = Array<string> | null;

// Source: src/sanity/whatDrivesUs.ts
// Variable: WHAT_DRIVES_US_QUERY
// Query: *[_id == "whatDrivesUs"][0]{    eyebrow,    headingLead,    headingAccent,    values[]{ icon, title, text }  }
export type WHAT_DRIVES_US_QUERY_RESULT =
  | {
      eyebrow: null;
      headingLead: null;
      headingAccent: null;
      values: null;
    }
  | {
      eyebrow: string;
      headingLead: string;
      headingAccent: string | null;
      values: Array<{
        icon: "client-focused" | "compassionate-approach" | "experienced";
        title: string;
        text: string;
      }>;
    }
  | {
      eyebrow: string;
      headingLead: string;
      headingAccent: string | null;
      values: null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_id == "aboutPage"][0]{\n    hero{ eyebrow, headingLead, headingAccent, headingTail, lead, ctaLabel },\n    whoWeAre{ eyebrow, headingLead, headingAccent, headingTail, paragraphs, ctaLabel },\n    promise{ quoteLead, quoteAccent, quoteTail },\n    meetPapa{ eyebrow, chips[]{ icon, value, label }, paragraphs, milestones[]{ when, title, text } },\n    whyFamilyLaw{ eyebrow, headingLead, headingAccent, headingTail, paragraphs }\n  }\n': ABOUT_PAGE_QUERY_RESULT;
    '{\n  "heading": *[_id == "awardsBand"][0].heading,\n  "badges": *[_type == "award"] | order(orderRank){\n    "id": _id,\n    alt,\n    width,\n    image{ asset, "dimensions": asset->metadata.dimensions }\n  }\n}': AWARDS_QUERY_RESULT;
    '\n  *[_id == "blogPage"][0]{ header{ eyebrow, title, intro } }\n': BLOG_PAGE_QUERY_RESULT;
    '\n  *[_type == "blogPost"]{\n    "id": slug.current,\n    "data": {\n      title,\n      date,\n      author,\n      "categories": coalesce(categories, []),\n      featured,\n      "keyTakeaways": coalesce(keyTakeaways, []),\n      "description": seo.metaDescription,\n      "seoTitle": seo.metaTitle,\n      "imageAlt": coalesce(image.alt, ""),\n      "image": image{\n        asset,\n        "dimensions": asset->metadata.dimensions\n      }\n    },\n    body,\n    "noIndex": seo.noIndex,\n    _updatedAt\n  }\n': BLOG_POSTS_ALL_QUERY_RESULT;
    '\n  *[_id == "clientPortalPage"][0]{\n    header{ kicker, title, deck },\n    groups[]{ heading, blurb, actions[]{ label, note, href, style, external, download } }\n  }\n': QUERY_RESULT;
    '\n  *[_id == "consultForm"][0]{\n    header{ eyebrow, headingLead, headingAccent, leadLines },\n    form{ cardTitle, cardIntro, submitLabel, privacyNote }\n  }\n': CONSULT_FORM_QUERY_RESULT;
    '\n  *[_id == "contactPage"][0]{\n    hero{ eyebrow, title, lead },\n    findUs{ eyebrow, headingLead, headingAccent, headingTail }\n  }\n': CONTACT_PAGE_QUERY_RESULT;
    '\n  *[_type == "faq"] | order(orderRank){ question, answer, shortAnswer, showOnHomepage }\n': FAQS_QUERY_RESULT;
    '*[_id == "firmDetails"][0]{\n  firmName,\n  tagline,\n  phone,\n  email,\n  address,\n  hours,\n  socials[]{ _key, platform, url },\n  serviceAreas[]{ _key, label, navLabel, href },\n  footerNav[]{ _key, heading, links[]{ _key, label, href } },\n  legalLinks[]{ _key, label, href }\n}': FIRM_DETAILS_QUERY_RESULT;
    '\n  *[_id == "homePage"][0]{\n    hero{ eyebrow, headingLines, headingAccent, lead, ctaLabel, stats[]{ value, label } },\n    about{\n      eyebrow, headingLead, headingAccent, videoLabel, videoCaption, body, ctaLabel,\n      video->{ "id": wistiaId, title, poster{ asset, "dimensions": asset->metadata.dimensions } }\n    },\n    practiceAreas{ eyebrow, headingLead, headingAccent, intro, ctaLabel, areas[]{ icon, title, href, text } },\n    featuredAttorney{ eyebrow, quote, paragraphs, ctaLabel, badgeYears, badgeLabelLines },\n    sellingPoints{ eyebrow, headingLead, headingAccent, points[]{ icon, title, text } },\n    faq{ eyebrow, headingLead, headingAccent },\n    videoReels{ eyebrow, headingLead, headingAccent, ctaLabel },\n    community{ eyebrow, headingLead, headingAccent, paragraphs, ctaLabel, tileTitle, tileText },\n    guideRequest{ eyebrow, headingLead, headingAccent, lead, offer },\n    blog{ eyebrow, headingLead, headingAccent, ctaLabel }\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_type == "locationPage"]{\n    "id": slug.current,\n    "data": {\n      title,\n      navLabel,\n      subtitle,\n      "parent": parent->slug.current,\n      "location": location->slug.current,\n      "description": seo.metaDescription,\n      "seoTitle": seo.metaTitle,\n      "faqs": coalesce(faqs[]{ _key, question, answer }, [])\n    },\n    body,\n    "noIndex": seo.noIndex,\n    "canonicalUrl": seo.canonicalUrl,\n    _updatedAt\n  }\n': LOCATION_PAGES_ALL_QUERY_RESULT;
    '\n  *[_type == "practiceArea"]{\n    "id": slug.current,\n    "data": {\n      title,\n      navLabel,\n      subtitle,\n      "parent": parent->slug.current,\n      "description": seo.metaDescription,\n      "seoTitle": seo.metaTitle,\n      "faqs": coalesce(faqs[]{ _key, question, answer }, [])\n    },\n    body,\n    "noIndex": seo.noIndex,\n    "canonicalUrl": seo.canonicalUrl,\n    _updatedAt\n  }\n': PRACTICE_AREAS_ALL_QUERY_RESULT;
    '\n  *[_id == "practiceAreasPage"][0]{\n    hero{ eyebrow, headingLead, headingAccent, headingTail, lead, ctaLabel },\n    featured{\n      eyebrow, headingLead, headingAccent, headingTail, lead,\n      cards[]{ areaId, label, icon, text }\n    },\n    allAreas{ eyebrow, headingLead, headingAccent, headingTail }\n  }\n': PRACTICE_AREAS_PAGE_QUERY_RESULT;
    '\n  *[_id == "caseEvaluationForm"][0]{ heading, intro, submitLabel, privacyNote }\n': SITE_WIDE_CASE_EVALUATION_QUERY_RESULT;
    '\n  *[_id == "attorney"][0]{\n    name,\n    role,\n    photo{ asset, "dimensions": asset->metadata.dimensions }\n  }\n': SITE_WIDE_ATTORNEY_QUERY_RESULT;
    '\n  *[_id == "statsBand"][0]{ stats[]{ value, label } }\n': STATS_BAND_QUERY_RESULT;
    '\n  *[_type == "testimonial"] | order(orderRank) {\n    _id, lead, body, name, matter\n  }\n': TESTIMONIALS_ALL_QUERY_RESULT;
    '\n  *[_id == "homePage"][0].about.pullQuote->{ _id, lead, body, name, matter }\n': TESTIMONIALS_PULL_QUOTE_QUERY_RESULT;
    '\n  *[_id == "testimonialsBand"][0]{\n    eyebrow, headingLead, headingAccent, lead, cardKicker, ctaLabel,\n    "picks": picks[]->{ _id, lead, body, name, matter }\n  }\n': TESTIMONIALS_BAND_QUERY_RESULT;
    '\n  *[_id == "testimonialsPage"][0]{\n    hero{ eyebrow, headingLead, headingAccent, headingTail, lead, ctaLabel },\n    wall{ eyebrow, headingLead, headingAccent, headingTail, lead, cardKicker }\n  }\n': TESTIMONIALS_PAGE_QUERY_RESULT;
    '\n  *[_type == "video"] | order(orderRank){\n    "id": wistiaId,\n    title,\n    label,\n    aspect,\n    poster{ asset, "dimensions": asset->metadata.dimensions },\n    reelPoster{ asset, "dimensions": asset->metadata.dimensions }\n  }\n': VIDEOS_QUERY_RESULT;
    '\n  *[_id == "homePage"][0].videoReels.picks[]->wistiaId\n': REEL_PICKS_QUERY_RESULT;
    '\n  *[_id == "whatDrivesUs"][0]{\n    eyebrow,\n    headingLead,\n    headingAccent,\n    values[]{ icon, title, text }\n  }\n': WHAT_DRIVES_US_QUERY_RESULT;
  }
}
