/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type FormField = {
  _type: "formField";
  label: string;
  placeholder?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  canonicalUrl?: string;
  noIndex?: boolean;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type NavLink = {
  _type: "navLink";
  label: string;
  href: string;
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  date: string;
  author: string;
  categories?: Array<
    "divorce" | "child-custody" | "child-support" | "domestic-violence"
  >;
  featured?: boolean;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  keyTakeaways?: Array<string>;
  body: BlockContent;
  legacyPath?: string;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type LocationPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "locationPage";
};

export type LocationPage = {
  _id: string;
  _type: "locationPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  navLabel: string;
  slug: Slug;
  location: LocationPageReference;
  parent?: LocationPageReference;
  subtitle?: string;
  body: BlockContent;
  faqs?: Array<{
    question: string;
    answer: BlockContent;
    _type: "faq";
    _key: string;
  }>;
  legacyPath?: string;
  seo?: Seo;
};

export type PracticeAreaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "practiceArea";
};

export type PracticeArea = {
  _id: string;
  _type: "practiceArea";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  navLabel: string;
  slug: Slug;
  parent?: PracticeAreaReference;
  subtitle?: string;
  body: BlockContent;
  faqs?: Array<{
    question: string;
    answer: BlockContent;
    _type: "faq";
    _key: string;
  }>;
  legacyPath?: string;
  seo?: Seo;
};

export type ConsultForm = {
  _id: string;
  _type: "consultForm";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: {
    eyebrow: string;
    headingLead: string;
    headingAccent?: string;
    leadLines: Array<string>;
  };
  details?: {
    callLabel: string;
    emailLabel: string;
    addressLabel: string;
    hoursLabel: string;
  };
  form?: {
    cardTitle: string;
    cardIntro: string;
    firstName: FormField;
    lastName: FormField;
    email: FormField;
    phone: FormField;
    message: FormField;
    submitLabel: string;
    privacyNote: string;
  };
};

export type TestimonialReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "testimonial";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  about?: {
    pullQuote: TestimonialReference;
  };
  testimonials?: {
    picks: Array<
      {
        _key: string;
      } & TestimonialReference
    >;
  };
  seo?: Seo;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  lead: string;
  body: string;
  name: string;
  matter: string;
};

export type FirmDetails = {
  _id: string;
  _type: "firmDetails";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firmName: string;
  tagline?: string;
  phone: string;
  email: string;
  address?: {
    street: string;
    locality: string;
    region: string;
    postalCode: string;
  };
  hours?: {
    days: string;
    time: string;
  };
  socials?: Array<{
    platform: "facebook" | "instagram" | "linkedin" | "x" | "youtube";
    url: string;
    _type: "socialProfile";
    _key: string;
  }>;
  serviceAreas?: Array<{
    label: string;
    navLabel: string;
    href: string;
    _type: "serviceArea";
    _key: string;
  }>;
  footerNav?: Array<{
    heading: string;
    links?: Array<
      {
        _key: string;
      } & NavLink
    >;
    _type: "footerColumn";
    _key: string;
  }>;
  legalLinks?: Array<
    {
      _key: string;
    } & NavLink
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | BlockContent
  | FormField
  | SanityImageAssetReference
  | Seo
  | NavLink
  | BlogPost
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | LocationPageReference
  | LocationPage
  | PracticeAreaReference
  | PracticeArea
  | ConsultForm
  | TestimonialReference
  | HomePage
  | Testimonial
  | FirmDetails
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/blogPosts.ts
// Variable: BLOG_POSTS_ALL_QUERY
// Query: *[_type == "blogPost"]{    "id": slug.current,    "data": {      title,      date,      author,      "categories": coalesce(categories, []),      featured,      "keyTakeaways": coalesce(keyTakeaways, []),      "description": seo.metaDescription,      "seoTitle": seo.metaTitle,      "imageAlt": coalesce(image.alt, ""),      "image": image{        asset,        "dimensions": asset->metadata.dimensions      }    },    body,    "noIndex": seo.noIndex,    _updatedAt  }
export type BLOG_POSTS_ALL_QUERY_RESULT = Array<{
  id: string;
  data: {
    title: string;
    date: string;
    author: string;
    categories:
      | Array<never>
      | Array<
          "child-custody" | "child-support" | "divorce" | "domestic-violence"
        >;
    featured: boolean | null;
    keyTakeaways: Array<string> | Array<never>;
    description: string | null;
    seoTitle: string | null;
    imageAlt: string | "";
    image: {
      asset: SanityImageAssetReference | null;
      dimensions: SanityImageDimensions | null;
    } | null;
  };
  body: BlockContent;
  noIndex: boolean | null;
  _updatedAt: string;
}>;

// Source: src/sanity/firmDetails.ts
// Variable: FIRM_DETAILS_QUERY
// Query: *[_id == "firmDetails"][0]{  firmName,  tagline,  phone,  email,  address,  hours,  socials[]{ _key, platform, url },  serviceAreas[]{ _key, label, navLabel, href },  footerNav[]{ _key, heading, links[]{ _key, label, href } },  legalLinks[]{ _key, label, href }}
export type FIRM_DETAILS_QUERY_RESULT =
  | {
      firmName: null;
      tagline: null;
      phone: null;
      email: null;
      address: null;
      hours: null;
      socials: null;
      serviceAreas: null;
      footerNav: null;
      legalLinks: null;
    }
  | {
      firmName: string;
      tagline: string | null;
      phone: string;
      email: string;
      address: {
        street: string;
        locality: string;
        region: string;
        postalCode: string;
      } | null;
      hours: {
        days: string;
        time: string;
      } | null;
      socials: Array<{
        _key: string;
        platform: "facebook" | "instagram" | "linkedin" | "x" | "youtube";
        url: string;
      }> | null;
      serviceAreas: Array<{
        _key: string;
        label: string;
        navLabel: string;
        href: string;
      }> | null;
      footerNav: Array<{
        _key: string;
        heading: string;
        links: Array<{
          _key: string;
          label: string;
          href: string;
        }> | null;
      }> | null;
      legalLinks: Array<{
        _key: string;
        label: string;
        href: string;
      }> | null;
    }
  | null;

// Source: src/sanity/locationPages.ts
// Variable: LOCATION_PAGES_ALL_QUERY
// Query: *[_type == "locationPage"]{    "id": slug.current,    "data": {      title,      navLabel,      subtitle,      "parent": parent->slug.current,      "location": location->slug.current,      "description": seo.metaDescription,      "seoTitle": seo.metaTitle,      "faqs": coalesce(faqs[]{ _key, question, answer }, [])    },    body,    "noIndex": seo.noIndex,    "canonicalUrl": seo.canonicalUrl,    _updatedAt  }
export type LOCATION_PAGES_ALL_QUERY_RESULT = Array<{
  id: string;
  data: {
    title: string;
    navLabel: string;
    subtitle: string | null;
    parent: string | null;
    location: string;
    description: string | null;
    seoTitle: string | null;
    faqs:
      | Array<{
          _key: string;
          question: string;
          answer: BlockContent;
        }>
      | Array<never>;
  };
  body: BlockContent;
  noIndex: boolean | null;
  canonicalUrl: string | null;
  _updatedAt: string;
}>;

// Source: src/sanity/practiceAreas.ts
// Variable: PRACTICE_AREAS_ALL_QUERY
// Query: *[_type == "practiceArea"]{    "id": slug.current,    "data": {      title,      navLabel,      subtitle,      "parent": parent->slug.current,      "description": seo.metaDescription,      "seoTitle": seo.metaTitle,      "faqs": coalesce(faqs[]{ _key, question, answer }, [])    },    body,    "noIndex": seo.noIndex,    "canonicalUrl": seo.canonicalUrl,    _updatedAt  }
export type PRACTICE_AREAS_ALL_QUERY_RESULT = Array<{
  id: string;
  data: {
    title: string;
    navLabel: string;
    subtitle: string | null;
    parent: string | null;
    description: string | null;
    seoTitle: string | null;
    faqs:
      | Array<{
          _key: string;
          question: string;
          answer: BlockContent;
        }>
      | Array<never>;
  };
  body: BlockContent;
  noIndex: boolean | null;
  canonicalUrl: string | null;
  _updatedAt: string;
}>;

// Source: src/sanity/testimonials.ts
// Variable: TESTIMONIALS_ALL_QUERY
// Query: *[_type == "testimonial"] | order(orderRank) {    _id, lead, body, name, matter  }
export type TESTIMONIALS_ALL_QUERY_RESULT = Array<{
  _id: string;
  lead: string;
  body: string;
  name: string;
  matter: string;
}>;

// Source: src/sanity/testimonials.ts
// Variable: TESTIMONIALS_HOME_QUERY
// Query: *[_id == "homePage"][0]{    "pullQuote": about.pullQuote->{ _id, lead, body, name, matter },    "picks": testimonials.picks[]->{ _id, lead, body, name, matter }  }
export type TESTIMONIALS_HOME_QUERY_RESULT =
  | {
      pullQuote: null;
      picks: null;
    }
  | {
      pullQuote: {
        _id: string;
        lead: string;
        body: string;
        name: string;
        matter: string;
      } | null;
      picks: Array<{
        _id: string;
        lead: string;
        body: string;
        name: string;
        matter: string;
      }> | null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "blogPost"]{\n    "id": slug.current,\n    "data": {\n      title,\n      date,\n      author,\n      "categories": coalesce(categories, []),\n      featured,\n      "keyTakeaways": coalesce(keyTakeaways, []),\n      "description": seo.metaDescription,\n      "seoTitle": seo.metaTitle,\n      "imageAlt": coalesce(image.alt, ""),\n      "image": image{\n        asset,\n        "dimensions": asset->metadata.dimensions\n      }\n    },\n    body,\n    "noIndex": seo.noIndex,\n    _updatedAt\n  }\n': BLOG_POSTS_ALL_QUERY_RESULT;
    '*[_id == "firmDetails"][0]{\n  firmName,\n  tagline,\n  phone,\n  email,\n  address,\n  hours,\n  socials[]{ _key, platform, url },\n  serviceAreas[]{ _key, label, navLabel, href },\n  footerNav[]{ _key, heading, links[]{ _key, label, href } },\n  legalLinks[]{ _key, label, href }\n}': FIRM_DETAILS_QUERY_RESULT;
    '\n  *[_type == "locationPage"]{\n    "id": slug.current,\n    "data": {\n      title,\n      navLabel,\n      subtitle,\n      "parent": parent->slug.current,\n      "location": location->slug.current,\n      "description": seo.metaDescription,\n      "seoTitle": seo.metaTitle,\n      "faqs": coalesce(faqs[]{ _key, question, answer }, [])\n    },\n    body,\n    "noIndex": seo.noIndex,\n    "canonicalUrl": seo.canonicalUrl,\n    _updatedAt\n  }\n': LOCATION_PAGES_ALL_QUERY_RESULT;
    '\n  *[_type == "practiceArea"]{\n    "id": slug.current,\n    "data": {\n      title,\n      navLabel,\n      subtitle,\n      "parent": parent->slug.current,\n      "description": seo.metaDescription,\n      "seoTitle": seo.metaTitle,\n      "faqs": coalesce(faqs[]{ _key, question, answer }, [])\n    },\n    body,\n    "noIndex": seo.noIndex,\n    "canonicalUrl": seo.canonicalUrl,\n    _updatedAt\n  }\n': PRACTICE_AREAS_ALL_QUERY_RESULT;
    '\n  *[_type == "testimonial"] | order(orderRank) {\n    _id, lead, body, name, matter\n  }\n': TESTIMONIALS_ALL_QUERY_RESULT;
    '\n  *[_id == "homePage"][0]{\n    "pullQuote": about.pullQuote->{ _id, lead, body, name, matter },\n    "picks": testimonials.picks[]->{ _id, lead, body, name, matter }\n  }\n': TESTIMONIALS_HOME_QUERY_RESULT;
  }
}
